# Generated by Django 3.0.5 on 2020-04-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Postapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about1', models.CharField(max_length=20)),
                ('body1', models.CharField(max_length=125)),
                ('title2', models.CharField(max_length=20)),
                ('body2', models.CharField(max_length=125)),
                ('title3', models.CharField(max_length=20)),
                ('body3', models.CharField(max_length=125)),
            ],
        ),
    ]
