$(document).ready(function(){

	$('.owl-carousel').owlCarousel({
		loop:true,
		autoplay:true,
		autoplayTimeout:2000,
		margin:50,
		 responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:4
        }
    }
	})
})